class_name AchievementCatalog
extends RefCounted

const CATEGORY_ORDER := {"General": 0, "Sudoku": 1, "Blockudoku": 2, "Shikaku": 3}
const TIER_ORDER := {"Bronze": 0, "Silver": 1, "Gold": 2}

const DEFINITIONS := {
	"first_game": {
		"id": "first_game",
		"category": "General",
		"title": "Getting Started",
		"description": "Play your first game.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "general.games_played", "threshold": 1},
	},
	"play_25": {
		"id": "play_25",
		"category": "General",
		"title": "Dedicated Player",
		"description": "Play 25 games total.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 25,
		"trigger": {"type": "stat", "key": "general.games_played", "threshold": 25},
	},
	"play_100": {
		"id": "play_100",
		"category": "General",
		"title": "Centurion",
		"description": "Play 100 games total.",
		"tier": "Silver",
		"hidden": true,
		"prerequisite_id": "play_25",
		"reward_type": "",
		"reward_id": "",
		"target_value": 100,
		"trigger": {"type": "stat", "key": "general.games_played", "threshold": 100},
	},
	"win_10": {
		"id": "win_10",
		"category": "General",
		"title": "Puzzle Winner",
		"description": "Win 10 games.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 10,
		"trigger": {"type": "stat", "key": "general.games_won", "threshold": 10},
	},
	"win_50": {
		"id": "win_50",
		"category": "General",
		"title": "Puzzle Veteran",
		"description": "Win 50 games.",
		"tier": "Silver",
		"hidden": true,
		"prerequisite_id": "win_10",
		"reward_type": "",
		"reward_id": "",
		"target_value": 50,
		"trigger": {"type": "stat", "key": "general.games_won", "threshold": 50},
	},
	"win_100": {
		"id": "win_100",
		"category": "General",
		"title": "Puzzle Legend",
		"description": "Win 100 games.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "win_50",
		"reward_type": "",
		"reward_id": "",
		"target_value": 100,
		"trigger": {"type": "stat", "key": "general.games_won", "threshold": 100},
	},
	"all_modes_session": {
		"id": "all_modes_session",
		"category": "General",
		"title": "Sampler Session",
		"description": "Use all 3 game modes in one session.",
		"tier": "Bronze",
		"hidden": true,
		"prerequisite_id": "",
		"reward_type": "shape",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "general.session_modes", "threshold": 3},
	},
	"streak_5": {
		"id": "streak_5",
		"category": "General",
		"title": "On a Roll",
		"description": "Win 5 games in a row.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 5,
		"trigger": {"type": "stat", "key": "general.current_win_streak", "threshold": 5},
		"progress_mode": "exact",
	},
	"streak_15": {
		"id": "streak_15",
		"category": "General",
		"title": "Unstoppable",
		"description": "Win 15 games in a row.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "streak_5",
		"reward_type": "",
		"reward_id": "",
		"target_value": 15,
		"trigger": {"type": "stat", "key": "general.current_win_streak", "threshold": 15},
		"progress_mode": "exact",
	},
	"sudoku_easy_win": {
		"id": "sudoku_easy_win",
		"category": "Sudoku",
		"title": "Easy Street",
		"description": "Complete an Easy Sudoku puzzle.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "sudoku.won_d0", "threshold": 1},
	},
	"sudoku_no_errors": {
		"id": "sudoku_no_errors",
		"category": "Sudoku",
		"title": "Clean Finish",
		"description": "Complete a Sudoku with no errors.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "theme",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "sudoku.perfect_wins", "threshold": 1},
	},
	"sudoku_under_5": {
		"id": "sudoku_under_5",
		"category": "Sudoku",
		"title": "Speed Demon",
		"description": "Complete any Sudoku in under 5 minutes.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "sudoku.wins_under_300s", "threshold": 1},
	},
	"sudoku_under_3": {
		"id": "sudoku_under_3",
		"category": "Sudoku",
		"title": "Lightning Fast",
		"description": "Complete any Sudoku in under 3 minutes.",
		"tier": "Silver",
		"hidden": true,
		"prerequisite_id": "sudoku_under_5",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "sudoku.wins_under_180s", "threshold": 1},
	},
	"sudoku_expert_win": {
		"id": "sudoku_expert_win",
		"category": "Sudoku",
		"title": "Expert Solver",
		"description": "Complete an Expert Sudoku puzzle.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "sudoku.won_d3", "threshold": 1},
	},
	"sudoku_evil_win": {
		"id": "sudoku_evil_win",
		"category": "Sudoku",
		"title": "Pure Evil",
		"description": "Complete an Evil Sudoku puzzle.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "sudoku_expert_win",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "sudoku.won_d4", "threshold": 1},
	},
	"sudoku_10_wins": {
		"id": "sudoku_10_wins",
		"category": "Sudoku",
		"title": "Sudoku Regular",
		"description": "Win 10 Sudoku games.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 10,
		"trigger": {"type": "stat", "key": "sudoku.games_won", "threshold": 10},
	},
	"sudoku_50_wins": {
		"id": "sudoku_50_wins",
		"category": "Sudoku",
		"title": "Sudoku Master",
		"description": "Win 50 Sudoku games.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "sudoku_10_wins",
		"reward_type": "",
		"reward_id": "",
		"target_value": 50,
		"trigger": {"type": "stat", "key": "sudoku.games_won", "threshold": 50},
	},
	"blockudoku_first_game": {
		"id": "blockudoku_first_game",
		"category": "Blockudoku",
		"title": "Block Party",
		"description": "Play your first Blockudoku game.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "blockudoku.games_completed", "threshold": 1},
	},
	"blockudoku_clear_three": {
		"id": "blockudoku_clear_three",
		"category": "Blockudoku",
		"title": "Triple Threat",
		"description": "Clear 3 lines or boxes at once in Blockudoku.",
		"tier": "Bronze",
		"hidden": true,
		"prerequisite_id": "",
		"reward_type": "effect",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.clear_count", "threshold": 3},
	},
	"blockudoku_score_100": {
		"id": "blockudoku_score_100",
		"category": "Blockudoku",
		"title": "Century",
		"description": "Score 100 or more in one Blockudoku game.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "blockudoku.high_score", "threshold": 100},
	},
	"blockudoku_10_games": {
		"id": "blockudoku_10_games",
		"category": "Blockudoku",
		"title": "Block Builder",
		"description": "Play 10 Blockudoku games.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "blockudoku_first_game",
		"reward_type": "",
		"reward_id": "",
		"target_value": 10,
		"trigger": {"type": "stat", "key": "blockudoku.games_completed", "threshold": 10},
	},
	"blockudoku_score_500": {
		"id": "blockudoku_score_500",
		"category": "Blockudoku",
		"title": "High Roller",
		"description": "Score 500 or more in one Blockudoku game.",
		"tier": "Silver",
		"hidden": true,
		"prerequisite_id": "blockudoku_score_100",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "blockudoku.high_score", "threshold": 500},
	},
	"blockudoku_50_clears": {
		"id": "blockudoku_50_clears",
		"category": "Blockudoku",
		"title": "Line Eraser",
		"description": "Clear 50 total lines or boxes in Blockudoku.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 50,
		"trigger": {"type": "stat", "key": "blockudoku.total_clears", "threshold": 50},
	},
	"blockudoku_score_1000": {
		"id": "blockudoku_score_1000",
		"category": "Blockudoku",
		"title": "Four Digits",
		"description": "Score 1000 or more in one Blockudoku game.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_score_500",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "blockudoku.high_score", "threshold": 1000},
	},
	"blockudoku_200_clears": {
		"id": "blockudoku_200_clears",
		"category": "Blockudoku",
		"title": "Clear Machine",
		"description": "Clear 200 total lines or boxes in Blockudoku.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_50_clears",
		"reward_type": "",
		"reward_id": "",
		"target_value": 200,
		"trigger": {"type": "stat", "key": "blockudoku.total_clears", "threshold": 200},
	},
	"blockudoku_clear_four": {
		"id": "blockudoku_clear_four",
		"category": "Blockudoku",
		"title": "Quad Clear",
		"description": "Clear 4 or more lines or boxes at once in Blockudoku.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_clear_three",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.clear_count", "threshold": 4},
	},
	"blockudoku_monster_clear": {
		"id": "blockudoku_monster_clear",
		"category": "Blockudoku",
		"title": "M-M-M-Monster Clear",
		"description": "Clear 5 or more lines or boxes at once in Blockudoku.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_clear_four",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.clear_count", "threshold": 5},
	},
	"blockudoku_combo_2": {
		"id": "blockudoku_combo_2",
		"category": "Blockudoku",
		"title": "Double Up",
		"description": "Achieve a 2x combo in Blockudoku.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.combo_count", "threshold": 2},
	},
	"blockudoku_combo_3": {
		"id": "blockudoku_combo_3",
		"category": "Blockudoku",
		"title": "Hat Trick",
		"description": "Achieve a 3x combo in Blockudoku.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "blockudoku_combo_2",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.combo_count", "threshold": 3},
	},
	"blockudoku_combo_4": {
		"id": "blockudoku_combo_4",
		"category": "Blockudoku",
		"title": "On Fire",
		"description": "Achieve a 4x combo in Blockudoku.",
		"tier": "Silver",
		"hidden": true,
		"prerequisite_id": "blockudoku_combo_3",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.combo_count", "threshold": 4},
	},
	"blockudoku_combo_5": {
		"id": "blockudoku_combo_5",
		"category": "Blockudoku",
		"title": "Unstoppable Streak",
		"description": "Achieve a 5x combo in Blockudoku.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_combo_4",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.combo_count", "threshold": 5},
	},
	"blockudoku_combo_6": {
		"id": "blockudoku_combo_6",
		"category": "Blockudoku",
		"title": "Combo God",
		"description": "Achieve a 6x combo in Blockudoku.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_combo_5",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.combo_count", "threshold": 6},
	},
	"blockudoku_clear_six": {
		"id": "blockudoku_clear_six",
		"category": "Blockudoku",
		"title": "Cleartacular",
		"description": "Clear 6 or more lines or boxes at once in Blockudoku.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_monster_clear",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.clear_count", "threshold": 6},
	},
	"blockudoku_clear_seven": {
		"id": "blockudoku_clear_seven",
		"category": "Blockudoku",
		"title": "Clearamanjaro",
		"description": "Clear 7 or more lines or boxes at once in Blockudoku.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "blockudoku_clear_six",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "event", "key": "blockudoku.clear_count", "threshold": 7},
	},
	"shikaku_first_win": {
		"id": "shikaku_first_win",
		"category": "Shikaku",
		"title": "Box Maker",
		"description": "Complete your first Shikaku puzzle.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "shikaku.games_won", "threshold": 1},
	},
	"shikaku_5x5_win": {
		"id": "shikaku_5x5_win",
		"category": "Shikaku",
		"title": "Small Boxes",
		"description": "Complete a 5×5 Shikaku puzzle.",
		"tier": "Bronze",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "shikaku.completed_s5", "threshold": 1},
	},
	"shikaku_10x10_win": {
		"id": "shikaku_10x10_win",
		"category": "Shikaku",
		"title": "Big Boxes",
		"description": "Complete a 10×10 Shikaku puzzle.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "shikaku.completed_s10", "threshold": 1},
	},
	"shikaku_10_wins": {
		"id": "shikaku_10_wins",
		"category": "Shikaku",
		"title": "Shikaku Regular",
		"description": "Complete 10 Shikaku puzzles.",
		"tier": "Silver",
		"hidden": false,
		"prerequisite_id": "shikaku_first_win",
		"reward_type": "",
		"reward_id": "",
		"target_value": 10,
		"trigger": {"type": "stat", "key": "shikaku.games_won", "threshold": 10},
	},
	"shikaku_under_60": {
		"id": "shikaku_under_60",
		"category": "Shikaku",
		"title": "Quick Rectangles",
		"description": "Complete any Shikaku puzzle in under 60 seconds.",
		"tier": "Silver",
		"hidden": true,
		"prerequisite_id": "shikaku_first_win",
		"reward_type": "",
		"reward_id": "",
		"target_value": 1,
		"trigger": {"type": "stat", "key": "shikaku.wins_under_60s", "threshold": 1},
	},
	"shikaku_streak_5": {
		"id": "shikaku_streak_5",
		"category": "Shikaku",
		"title": "Box Streak",
		"description": "Win 5 Shikaku puzzles in a row.",
		"tier": "Gold",
		"hidden": true,
		"prerequisite_id": "shikaku_10_wins",
		"reward_type": "",
		"reward_id": "",
		"target_value": 5,
		"trigger": {"type": "stat", "key": "shikaku.current_streak", "threshold": 5},
		"progress_mode": "exact",
	},
}
