class_name EclipseGridLogic
extends RefCounted

## Pure logic layer for Eclipse Grid.
##
## Owns state, validation, hint application, and UndoStack without any
## Node or autoload dependencies.
##
## Cells are stored as a flat Array[int] of size×size:
##   0 = EMPTY, 1 = PLUS, 2 = MINUS.
##
## Relations:
##   h_relations[Vector2i(col, row)] = EQ or NEQ  (between (col,row) and (col+1,row))
##   v_relations[Vector2i(col, row)] = EQ or NEQ  (between (col,row) and (col,row+1))

const EMPTY := EclipseGridSolver.EMPTY
const PLUS  := EclipseGridSolver.PLUS
const MINUS := EclipseGridSolver.MINUS
const EQ    := EclipseGridSolver.EQ
const NEQ   := EclipseGridSolver.NEQ

const SCHEMA_VERSION := 1

## Assistance modes
const ASSIST_NONE   := 0   ## No assistance
const ASSIST_FREE   := 1   ## Highlight errors, no penalty
const ASSIST_STRICT := 2   ## Reject incorrect entries

# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

var size: int = 0
var random_seed: int = 0

var givens: Array[int] = []      ## Fixed cells (non-empty = immutable)
var cells: Array[int] = []       ## Current player state (may include EMPTY)
var solution: Array[int] = []    ## Complete solution for hints
var h_relations: Dictionary = {} ## Horizontal clues
var v_relations: Dictionary = {} ## Vertical clues

var is_completed: bool = false
var hints_used: int = 0
## Changing assistance_mode clears any pending rejected cycle state so that
## cycle_cell() always restarts from the current accepted cell value.
var assistance_mode: int = ASSIST_FREE:
	set(value):
		assistance_mode = value
		_rejected_cells.clear()

var _undo_stack: UndoStack = UndoStack.new()

## Tracks the last-rejected glyph for cells in strict mode where a wrong
## glyph was entered.  The rejected glyph is stored here instead of in
## cells[], keeping cells[] at the last accepted (visible) value.  Cleared
## when the cell receives an accepted placement or is restored via undo.
var _rejected_cells: Dictionary = {}

var undo_stack: Array[Dictionary]:
	get:
		return _undo_stack.get_undo_entries()

var redo_stack: Array[Dictionary]:
	get:
		return _undo_stack.get_redo_entries()


# ---------------------------------------------------------------------------
# Result classes
# ---------------------------------------------------------------------------

class SetGlyphResult:
	var index: int = -1
	var old_value: int = EclipseGridSolver.EMPTY
	var new_value: int = EclipseGridSolver.EMPTY
	var rejected: bool = false   ## Strict mode rejected an incorrect entry
	var game_won: bool = false


class HintResult:
	var index: int = -1
	var value: int = EclipseGridSolver.EMPTY
	var game_won: bool = false
	var had_step: bool = false


class UndoRedoResult:
	var index: int = -1
	var old_value: int = EclipseGridSolver.EMPTY
	var new_value: int = EclipseGridSolver.EMPTY


# ---------------------------------------------------------------------------
# Initialization
# ---------------------------------------------------------------------------

## Start a new game by generating a puzzle.  Call from the main thread or
## pass data already generated by the background thread.
func init_new_game(puzzle_size: int, seed_value: int, generated: Dictionary = {}) -> void:
	size = puzzle_size
	random_seed = seed_value

	var data: Dictionary = generated
	if data.is_empty():
		data = EclipseGridGenerator.generate(size, seed_value)

	if data.is_empty():
		push_error("EclipseGridLogic: generation failed for size=%d seed=%d" % [size, seed_value])
		return

	_apply_generated_data(data)
	_undo_stack.clear()
	_rejected_cells.clear()
	is_completed = false
	hints_used = 0


func init_from_save(data: Dictionary) -> void:
	var ver := int(data.get("schema_version", 0))
	if ver > SCHEMA_VERSION:
		push_warning("EclipseGridLogic: unknown schema version %d" % ver)

	size = int(data.get("size", 0))
	random_seed = int(data.get("seed", 0))
	givens = _deserialize_array(data.get("givens", []))
	cells = _deserialize_array(data.get("cells", []))
	solution = _deserialize_array(data.get("solution", []))
	h_relations = _deserialize_relations(data.get("h_relations", {}))
	v_relations = _deserialize_relations(data.get("v_relations", {}))
	is_completed = bool(data.get("is_completed", false))
	hints_used = int(data.get("hints_used", 0))
	assistance_mode = int(data.get("assistance_mode", ASSIST_FREE))

	var undo_entries := _deserialize_undo_stack(data.get("undo_stack", []))
	var redo_entries := _deserialize_undo_stack(data.get("redo_stack", []))
	_undo_stack.load_entries(undo_entries, redo_entries)
	_rejected_cells = _deserialize_rejected_cells(data.get("rejected_cells", {}))

	_recompute_completion()


func serialize() -> Dictionary:
	return {
		"schema_version": SCHEMA_VERSION,
		"size": size,
		"seed": random_seed,
		"givens": _serialize_array(givens),
		"cells": _serialize_array(cells),
		"solution": _serialize_array(solution),
		"h_relations": _serialize_relations(h_relations),
		"v_relations": _serialize_relations(v_relations),
		"is_completed": is_completed,
		"hints_used": hints_used,
		"assistance_mode": assistance_mode,
		"undo_stack": _serialize_undo_stack(_undo_stack.get_undo_entries()),
		"redo_stack": _serialize_undo_stack(_undo_stack.get_redo_entries()),
		"rejected_cells": _serialize_rejected_cells(_rejected_cells),
	}


# ---------------------------------------------------------------------------
# Gameplay
# ---------------------------------------------------------------------------

## Cycle the cell at the given index: EMPTY → PLUS → MINUS → EMPTY.
## Returns a SetGlyphResult describing what happened.
func cycle_cell(index: int) -> SetGlyphResult:
	var result := SetGlyphResult.new()
	result.index = index
	if index < 0 or index >= cells.size():
		return result
	if _is_given(index):
		return result
	if is_completed:
		return result

	# Advance the cycle from the rejected position (if any) rather than from
	# the visible accepted value.  This lets the player keep tapping through
	# wrong choices without the cycle restarting from EMPTY each time.
	var cycle_from: int = _rejected_cells.get(index, cells[index])
	var new_val: int = _next_value(cycle_from)

	# result.old_value always reflects the visible (accepted) board state.
	result.old_value = cells[index]

	# Strict mode: EMPTY (erase) is always accepted; any non-EMPTY wrong entry
	# is recorded in _rejected_cells without touching cells[], so the board
	# never renders a rejected glyph.
	if assistance_mode == ASSIST_STRICT and new_val != EMPTY:
		if not solution.is_empty() and new_val != solution[index]:
			result.new_value = new_val
			result.rejected = true
			_rejected_cells[index] = new_val
			# cells[index] is intentionally NOT updated — keeps the last accepted value
			return result

	# Accepted placement: clear any pending rejected cycle position.
	_rejected_cells.erase(index)
	result.new_value = new_val

	# Avoid phantom no-op undo entries (e.g. EMPTY → rejections → EMPTY erase).
	# old_value for undo is cells[index] — always the clean accepted state.
	if cells[index] != new_val:
		_undo_stack.push({"index": index, "old_value": cells[index], "new_value": new_val})
	cells[index] = new_val
	_recompute_completion()
	result.game_won = is_completed
	return result


## Directly set a cell value (for replay/hint application).
## Skips strict mode and undo recording.
func set_cell_direct(index: int, value: int) -> void:
	if index < 0 or index >= cells.size():
		return
	cells[index] = value
	_rejected_cells.erase(index)
	_recompute_completion()


## Apply one hint step from the human solver.
func use_hint() -> HintResult:
	var result := HintResult.new()
	if is_completed or solution.is_empty():
		return result

	# Provide a clean board state to the solver: any cell the player has filled
	# incorrectly (free mode) is reset to EMPTY so the solver derives deductions
	# from a consistent, solution-compatible state rather than propagating player
	# mistakes into incorrect hint values.
	# cells[] never holds rejected glyphs (strict mode keeps them in _rejected_cells),
	# so no additional cleaning is required here.
	var clean_cells: Array[int] = cells.duplicate()
	for i in clean_cells.size():
		if clean_cells[i] != EMPTY and clean_cells[i] != solution[i]:
			clean_cells[i] = EMPTY

	var analysis: EclipseGridSolver.Analysis = EclipseGridSolver.analyze(
			size, clean_cells, h_relations, v_relations)
	if analysis.steps.is_empty():
		return result

	var step: EclipseGridSolver.SolverStep = analysis.steps[0]
	if step.affected_cells.is_empty():
		return result

	var idx: int = step.affected_cells[0]
	var val: int = step.result_value

	# Guard: the derived value must match the known solution.
	if val != solution[idx]:
		return result

	# Skip cells already correctly filled.
	if cells[idx] == val:
		return result

	result.had_step = true
	result.index = idx
	result.value = val

	# cells[idx] is always the accepted state — use it directly as undo old_value.
	_rejected_cells.erase(idx)
	_undo_stack.push({"index": idx, "old_value": cells[idx], "new_value": val})
	cells[idx] = val
	hints_used += 1
	_recompute_completion()
	result.game_won = is_completed
	return result


## Undo the last move.
func undo() -> UndoRedoResult:
	var result := UndoRedoResult.new()
	if not can_undo():
		return result
	var entry: Dictionary = _undo_stack.undo()
	var idx: int = int(entry.get("index", -1))
	if idx < 0 or idx >= cells.size():
		return result
	var old_val: int = int(entry.get("old_value", EMPTY))
	var new_val: int = int(entry.get("new_value", EMPTY))
	cells[idx] = old_val
	_rejected_cells.erase(idx)  # Clear any pending rejected cycle position
	_recompute_completion()
	result.index = idx
	result.old_value = new_val
	result.new_value = old_val
	return result


## Redo a previously undone move.
func redo() -> UndoRedoResult:
	var result := UndoRedoResult.new()
	if not can_redo():
		return result
	var entry: Dictionary = _undo_stack.redo()
	var idx: int = int(entry.get("index", -1))
	if idx < 0 or idx >= cells.size():
		return result
	var new_val: int = int(entry.get("new_value", EMPTY))
	var old_val: int = int(entry.get("old_value", EMPTY))
	cells[idx] = new_val
	_rejected_cells.erase(idx)
	_recompute_completion()
	result.index = idx
	result.old_value = old_val
	result.new_value = new_val
	return result


func can_undo() -> bool:
	return not is_completed and _undo_stack.can_undo()


func can_redo() -> bool:
	return not is_completed and _undo_stack.can_redo()


## Return the set of indices with rule violations (for free assistance display).
func get_error_cells() -> Array[int]:
	var errors: Array[int] = []
	if size == 0 or cells.is_empty():
		return errors
	var half := size / 2
	# Run violations per row and column
	for r in size:
		var plus := 0
		var minus := 0
		for c in size:
			var v: int = cells[r * size + c]
			if v == PLUS:
				plus += 1
			elif v == MINUS:
				minus += 1
		if plus > half or minus > half:
			for c in size:
				if not errors.has(r * size + c):
					errors.append(r * size + c)
		# No-three check
		for c in range(2, size):
			var a: int = cells[r * size + c - 2]
			var b: int = cells[r * size + c - 1]
			var cv: int = cells[r * size + c]
			if a != EMPTY and a == b and b == cv:
				for i in [r * size + c - 2, r * size + c - 1, r * size + c]:
					if not errors.has(i):
						errors.append(i)
	for c in size:
		var plus := 0
		var minus := 0
		for r in size:
			var v: int = cells[r * size + c]
			if v == PLUS:
				plus += 1
			elif v == MINUS:
				minus += 1
		if plus > half or minus > half:
			for r in size:
				if not errors.has(r * size + c):
					errors.append(r * size + c)
		for r in range(2, size):
			var a: int = cells[(r - 2) * size + c]
			var b: int = cells[(r - 1) * size + c]
			var cv: int = cells[r * size + c]
			if a != EMPTY and a == b and b == cv:
				for i in [(r - 2) * size + c, (r - 1) * size + c, r * size + c]:
					if not errors.has(i):
						errors.append(i)
	# Relation violations
	for pos in h_relations.keys():
		var cell: Vector2i = pos
		var rel: int = h_relations[pos]
		var li: int = cell.y * size + cell.x
		var ri: int = cell.y * size + (cell.x + 1)
		var lv: int = cells[li]
		var rv: int = cells[ri]
		if lv != EMPTY and rv != EMPTY:
			var violated := (rel == EQ and lv != rv) or (rel == NEQ and lv == rv)
			if violated:
				if not errors.has(li):
					errors.append(li)
				if not errors.has(ri):
					errors.append(ri)
	for pos in v_relations.keys():
		var cell: Vector2i = pos
		var rel: int = v_relations[pos]
		var ti: int = cell.y * size + cell.x
		var bi: int = (cell.y + 1) * size + cell.x
		var tv: int = cells[ti]
		var bv: int = cells[bi]
		if tv != EMPTY and bv != EMPTY:
			var violated := (rel == EQ and tv != bv) or (rel == NEQ and tv == bv)
			if violated:
				if not errors.has(ti):
					errors.append(ti)
				if not errors.has(bi):
					errors.append(bi)
	return errors


## Return broken relation pairs [(li, ri), ...] for free assistance.
func get_broken_relations() -> Array[Array]:
	var broken: Array[Array] = []
	for pos in h_relations.keys():
		var cell: Vector2i = pos
		var rel: int = h_relations[pos]
		var li: int = cell.y * size + cell.x
		var ri: int = cell.y * size + (cell.x + 1)
		var lv: int = cells[li]
		var rv: int = cells[ri]
		if lv != EMPTY and rv != EMPTY:
			if (rel == EQ and lv != rv) or (rel == NEQ and lv == rv):
				broken.append([li, ri, true])  # true = horizontal
	for pos in v_relations.keys():
		var cell: Vector2i = pos
		var rel: int = v_relations[pos]
		var ti: int = cell.y * size + cell.x
		var bi: int = (cell.y + 1) * size + cell.x
		var tv: int = cells[ti]
		var bv: int = cells[bi]
		if tv != EMPTY and bv != EMPTY:
			if (rel == EQ and tv != bv) or (rel == NEQ and tv == bv):
				broken.append([ti, bi, false])  # false = vertical
	return broken


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

func _is_given(index: int) -> bool:
	return index >= 0 and index < givens.size() and givens[index] != EMPTY


func _next_value(v: int) -> int:
	match v:
		EMPTY: return PLUS
		PLUS:  return MINUS
		_:     return EMPTY


func _recompute_completion() -> void:
	if cells.is_empty():
		is_completed = false
		return
	for v in cells:
		if v == EMPTY:
			is_completed = false
			return
	is_completed = EclipseGridSolver.validate(size, cells, h_relations, v_relations)


func _apply_generated_data(data: Dictionary) -> void:
	givens = _deserialize_array(data.get("givens", []))
	solution = _deserialize_array(data.get("solution", []))
	h_relations = _deserialize_relations(data.get("h_relations", {}))
	v_relations = _deserialize_relations(data.get("v_relations", {}))
	cells = givens.duplicate()


# ---------------------------------------------------------------------------
# Serialization helpers
# ---------------------------------------------------------------------------

func _serialize_array(arr: Array[int]) -> Array:
	var out: Array = []
	out.assign(arr)
	return out


func _deserialize_array(data: Variant) -> Array[int]:
	var result: Array[int] = []
	if data is Array:
		for v in data:
			result.append(int(v))
	return result


func _serialize_relations(rels: Dictionary) -> Dictionary:
	var out: Dictionary = {}
	for pos in rels.keys():
		var cell: Vector2i = pos
		out["%d,%d" % [cell.x, cell.y]] = int(rels[pos])
	return out


func _deserialize_relations(data: Variant) -> Dictionary:
	var result: Dictionary = {}
	if not (data is Dictionary):
		return result
	for key in data.keys():
		if key is Vector2i:
			result[key] = int(data[key])
			continue
		var parts: PackedStringArray = str(key).split(",")
		if parts.size() == 2:
			result[Vector2i(int(parts[0]), int(parts[1]))] = int(data[key])
	return result


func _serialize_undo_stack(stack: Array[Dictionary]) -> Array:
	var out: Array = []
	for entry in stack:
		out.append({
			"index": int(entry.get("index", -1)),
			"old_value": int(entry.get("old_value", EMPTY)),
			"new_value": int(entry.get("new_value", EMPTY)),
		})
	return out


func _deserialize_undo_stack(data: Variant) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	if data is Array:
		for entry in data:
			if entry is Dictionary:
				result.append({
					"index": int(entry.get("index", -1)),
					"old_value": int(entry.get("old_value", EMPTY)),
					"new_value": int(entry.get("new_value", EMPTY)),
				})
	return result


## Serialize _rejected_cells as {"idx": glyph_int, ...} using string keys.
## Values are always PLUS or MINUS (never EMPTY).
func _serialize_rejected_cells(rc: Dictionary) -> Dictionary:
	var out: Dictionary = {}
	for key in rc.keys():
		out[str(int(key))] = int(rc[key])
	return out


## Restore _rejected_cells from serialized form.  Unknown or invalid entries
## are silently dropped (saves without rejected_cells use an empty dict).
func _deserialize_rejected_cells(data: Variant) -> Dictionary:
	var result: Dictionary = {}
	if not (data is Dictionary):
		return result
	var max_idx: int = cells.size()
	for key in data.keys():
		var idx: int = int(str(key))
		if idx < 0 or idx >= max_idx:
			continue
		var val: int = int(data[key])
		if val == PLUS or val == MINUS:
			result[idx] = val
	return result
